### ISSUE TITLE
sortOrder doesn't get cleared on  route change

### ISSUE THREAD

**Issue by yabdelmonem** [mwaylabs/uikit#202]
How to reproduce (see MDM-15440):

- Setup app publishing
- Add one target to an app
- In the publishing overview: Sort by "Provider" (in the url a new parameter gets applied (s=targetProvider)
- Switch to the app history
- Expected: The app history gets displayed.

**Comment by stefanjauker** [comment]
```
2018-05-22 14:49:53.553 ERROR 28781 [NIO-3 task-3] usIntegrationServiceImpl: Getting continuous integrations with GetQuery failed: GetQuery [limit=30, offset=0, sortOrder=-true, filter=null, getNonpagedCount=true, getItems=true, fields=null, caseSensitive=null] [authorization=D5062EB9-A141-4039-9683-6165A2B868A4, request=00000163-87e6-178c-0000-000000000980]
java.lang.IllegalArgumentException: The attribute [true] is not present in the managed type [EntityTypeImpl@982532336:ContinuousIntegration [ javaType: class com.mwaysolutions.relution.appstore.environment.domain.devhub.ContinuousIntegration descriptor: RelationalDescriptor(com.mwaysolutions.relution.appstore.environment.domain.devhub.ContinuousIntegration --> [DatabaseTable(mam_cntns_intgrtn), DatabaseTable(mam_cntns_intgrtn_dtl)]), mappings: 9]].
	at org.eclipse.persistence.internal.jpa.metamodel.ManagedTypeImpl.getAttribute(ManagedTypeImpl.java:149)
	at org.eclipse.persistence.internal.jpa.querydef.FromImpl.get(FromImpl.java:323)
	at com.mwaysolutions.gofer2.filter.jpa.JpaVisitor.getPath(JpaVisitor.java:150)
	at com.mwaysolutions.relution.common.dao.impl.RelutionDaoImpl.get_aroundBody0(RelutionDaoImpl.java:160)
	at com.mwaysolutions.relution.common.dao.impl.RelutionDaoImpl$AjcClosure1.run(RelutionDaoImpl.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at com.mwaysolutions.relution.common.dao.impl.RelutionDaoImpl.get(RelutionDaoImpl.java:116)
	at com.mwaysolutions.relution.appstore.environment.service.impl.ContinuousIntegrationServiceImpl.getContinuousIntegrations(ContinuousIntegrationServiceImpl.java:99)
```

**Comment by Zarlex** [comment]
Should be fixed with this PR https://github.com/mwaylabs/uikit/pull/208

**Comment by yabdelmonem** [comment]
See:
MDM-14899, MDM-15351, MDM-15660

**Comment by yabdelmonem** [comment]
The issue:
```
2018-05-22 14:49:53.553 ERROR 28781 [NIO-3 task-3] usIntegrationServiceImpl: Getting continuous integrations with GetQuery failed: GetQuery [limit=30, offset=0, sortOrder=-true, filter=null, getNonpagedCount=true, getItems=true, fields=null, caseSensitive=null] [authorization=D5062EB9-A141-4039-9683-6165A2B868A4, request=00000163-87e6-178c-0000-000000000980]
java.lang.IllegalArgumentException: The attribute [true] is not present in the managed type [EntityTypeImpl@982532336:ContinuousIntegration [ javaType: class com.mwaysolutions.relution.appstore.environment.domain.devhub.ContinuousIntegration descriptor: RelationalDescriptor(com.mwaysolutions.relution.appstore.environment.domain.devhub.ContinuousIntegration --> [DatabaseTable(mam_cntns_intgrtn), DatabaseTable(mam_cntns_intgrtn_dtl)]), mappings: 9]].
	at org.eclipse.persistence.internal.jpa.metamodel.ManagedTypeImpl.getAttribute(ManagedTypeImpl.java:149)
	at org.eclipse.persistence.internal.jpa.querydef.FromImpl.get(FromImpl.java:323)
	at com.mwaysolutions.gofer2.filter.jpa.JpaVisitor.getPath(JpaVisitor.java:150)
	at com.mwaysolutions.relution.common.dao.impl.RelutionDaoImpl.get_aroundBody0(RelutionDaoImpl.java:160)
	at com.mwaysolutions.relution.common.dao.impl.RelutionDaoImpl$AjcClosure1.run(RelutionDaoImpl.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at com.mwaysolutions.relution.common.dao.impl.RelutionDaoImpl.get(RelutionDaoImpl.java:116)
	at com.mwaysolutions.relution.appstore.environment.service.impl.ContinuousIntegrationServiceImpl.getContinuousIntegrations(ContinuousIntegrationServiceImpl.java:99)
```
Is still open.
How to reproduce:
- Follow the quick test to setup the dev hub
- In the modal where you can link a repository (add repository modal) sort by project name
- Expected: The list gets sorted
- Actual: The modal closes, the sort order gets applied in the url, the portal makes a redirect to the new url and it ends up in the described 500 error.
- Also it is not possible to remove the sort order manually in the url.
